DjangoChatApp/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path("", index, name="home"),
    path("account_view/<user_id>/", account_view, name="account_view"),
    path("account_search/", account_search_view, name="account_search_view")
]

DjangoChatProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("DjangoChatApp.urls")),
    path("account/", include("account.urls")),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)
    

account/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [

    path("register/", register, name="register"),
    path("login/", loginform,name="login"),
    path("logout/", logoutform, name="logout"),
    path("edit_account/<user_id>/", edit_account_view, name="edit_account"),

    
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_reset/password_change_done.html'),name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='account/password_reset/password_change.html'),name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset/password_reset_complete.html'), name='password_reset_complete'),
    
]

DjangoChatApp/models.py
from django.db import models

# Create your models here.

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os
 

class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
			email=self.email,
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.email,
			password=password,
			username=username,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user


def get_profile_image_filepath(self, filename):
	return 'profile_images/' + str(self.pk) + '/profile_image.png'

def get_default_profile_image():
	return "images/puser.svg"


class Account(AbstractBaseUser):
	email 					= models.EmailField(verbose_name="email", max_length=60, unique=True)
	username 				= models.CharField(max_length=30, unique=True)
	date_joined				= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login				= models.DateTimeField(verbose_name='last login', auto_now=True)
	is_admin				= models.BooleanField(default=False)
	is_active				= models.BooleanField(default=True)
	is_staff				= models.BooleanField(default=False)
	is_superuser			= models.BooleanField(default=False)
	profile_image			= models.ImageField(max_length=255, upload_to=get_profile_image_filepath, null=True, blank=True, default=get_default_profile_image)
	hide_email				= models.BooleanField(default=True)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username']

	objects = MyAccountManager()

	def __str__(self):
		return self.username

	def get_profile_image_filename(self):
		return str(self.profile_image)[str(self.profile_image).index('profile_images/' + str(self.pk) + "/"):]

	# For checking permissions. to keep it simple all admin have ALL permissons
	def has_perm(self, perm, obj=None):
		return self.is_admin

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
	def has_module_perms(self, app_label):
		return True

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import Account

 
class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

	class Meta:
		model = Account
		fields = ('email', 'username', 'password1', 'password2', )

	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % email)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)


class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")


class AccountUpdateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('username', 'email', 'profile_image', 'hide_email')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.exclude(
            	pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError('Email "%s" is already in use.' % account)

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            account = Account.objects.exclude(
            	pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            return username
        raise forms.ValidationError(
            'Username "%s" is already in use.' % username)

    def save(self, commit=True):
        account = super(AccountUpdateForm, self).save(commit=False)
        account.username = self.cleaned_data['username']
        account.email = self.cleaned_data['email'].lower()
        account.profile_image = self.cleaned_data['profile_image']
        account.hide_email = self.cleaned_data['hide_email']
        if commit:
            account.save()
        return account

DjangoChatApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from account.models import *

def index(request):
    return render(request, "DjangoChatApp/index.html")

def account_view(request, *args, **kwargs):

	context = {}
	user_id = kwargs.get("user_id")
	try:
		account = Account.objects.get(pk=user_id)
	except:
		return HttpResponse("Something went wrong.")
	if account:
		context['id'] = account.id
		context['username'] = account.username
		context['email'] = account.email
		context['profile_image'] = account.profile_image.url
		context['hide_email'] = account.hide_email

		# Define template variables
		is_self = True
		is_friend = False
		user = request.user
		if user.is_authenticated and user != account:
			is_self = False
		elif not user.is_authenticated:
			is_self = False

		# Set the template variables to the values
		context['is_self'] = is_self
		context['is_friend'] = is_friend
		context['BASE_URL'] = settings.BASE_URL
		return render(request, "DjangoChatApp/account.html", context)


def account_search_view(request, *args, **kwargs):
	context = {}
	if request.method == "GET":
		search_query = request.GET.get("q")
		if len(search_query) > 0:
			search_results = Account.objects.filter(email__icontains=search_query) | Account.objects.filter(username__icontains=search_query)
			search_results = search_results.distinct()
			accounts = []
			for account in search_results:
				accounts.append((account,False))
			context['accounts'] = accounts
	return render(request, "DjangoChatApp/search_results.html",context)

account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate,logout
from .forms import *
from django.conf import settings
 
def register(request, *args, **kwargs):
	user = request.user
	if user.is_authenticated:
		return HttpResponse("You are already authenticated as " + str(user.email))

	context = {}
	if request.POST:
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			email = form.cleaned_data.get('email').lower()
			raw_password = form.cleaned_data.get('password1')
			account = authenticate(email=email, password=raw_password)
			login(request, account)
			destination = get_redirect_if_exitst(request)
			if destination:
				return redirect(destination)
			return redirect('home')
		else:
			context['registration_form'] = form

	else:
		form = RegistrationForm()
		context['registration_form'] = form
	return render(request, 'account/register.html', context)


def loginform(request, *args, **kwargs):
	context = {}

	user = request.user
	if user.is_authenticated:
		return redirect("home")

	destination = get_redirect_if_exitst(request)
	print("destination: " + str(destination))

	if request.POST:
		form = AccountAuthenticationForm(request.POST)
		if form.is_valid():
			email = request.POST['email']
			password = request.POST['password']
			user = authenticate(email=email, password=password)

			if user:
				login(request, user)
				if destination:
					return redirect(destination)
				return redirect("home")

	else:
		form = AccountAuthenticationForm()

	context['login_form'] = form

	return render(request, "account/login.html", context)

def logoutform(request):
    logout(request)
    return redirect("home")

def get_redirect_if_exitst(request):
    redirect = None
    if request.GET:
        if request.GET.get("next"):
            redirect = str(request.GET.get("next"))
    return redirect


def edit_account_view(request, *args, **kwargs):
	if not request.user.is_authenticated:
		return redirect("login")
	user_id = kwargs.get("user_id")
	account = Account.objects.get(pk=user_id)
	if account.pk != request.user.pk:
		return HttpResponse("You cannot edit someone elses profile.")
	context = {}
	if request.POST:
		form = AccountUpdateForm(request.POST, request.FILES, instance=request.user)
		if form.is_valid():
			account.profile_image.delete()
			form.save()
			new_username = form.cleaned_data['username']
			return redirect("account_view", user_id=account.pk)
		else:
			form = AccountUpdateForm(request.POST, instance=request.user,
				initial={
					"id": account.pk,
					"email": account.email, 
					"username": account.username,
					"profile_image": account.profile_image,
					"hide_email": account.hide_email,
				}
			)
			context['form'] = form
	else:
		form = AccountUpdateForm(
			initial={
					"id": account.pk,
					"email": account.email, 
					"username": account.username,
					"profile_image": account.profile_image,
					"hide_email": account.hide_email,
				}
			)
		context['form'] = form
	context['DATA_UPLOAD_MAX_MEMORY_SIZE'] = settings.DATA_UPLOAD_MAX_MEMORY_SIZE
	return render(request, "DjangoChatApp/edit_account.html", context)

templates/DjangoChatApp/account.html
{% extends '../base.html' %}
{% load static %}

{% block content %}


<div class="container-fluid">
    <div class="d-flex flex-row justify-content-center flex-wrap align-items-start">

        <div class="card profile-card m-2">
            <div class="card-body">
                <div class="d-flex flex-column justify-content-center p-4">
                    <div class="image-container mx-auto mb-4">
                        <img class="d-block border border-dark rounded-circle img-fluid mx-auto profile-image"
                            alt="codingwithmitch logo" id="id_profile_image" src="{{profile_image}}">
                    </div>
                    <p class="mt-4 mb-1 field-heading">Email</p>
                    {% if is_self %}
                    <h5>{{email}}</h5>
                    {% else %}
                    {% if hide_email %}
                    <h5>**********</h5>
                    {% else %}
                    <h5>{{email}}</h5>
                    {% endif %}
                    {% endif %}
                    <p class="mt-4 mb-1 field-heading">Username</p>
                    <h5>{{username}}</h5>

                    <!-- If Auth user is viewing their own profile -->
                    {% if is_self %}
                    <a class="mt-4 btn btn-primary" href="{% url 'edit_account' user_id=id %}">Update</a>
                    <div class="d-flex flex-column mt-4">
                        <a class="m-auto" href="{% url 'password_change' %}">Change password</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if request.user.is_authenticated %}
        <div class="d-flex flex-column mb-4">

            <!-- THEM to YOU -->
            {% if request_sent == 0 %}
            <div class="card m-2 p-4">
                <div class="d-flex flex-row align-items-center">
                    <span class="friend-text align-items-center mr-2">Accept Friend Request</span>
                    <span id="id_cancel_{{id}}" class="decline-friend-request material-icons p-1"
                        onclick='triggerDeclineFriendRequest("{{pending_friend_request_id}}")'>cancel</span>
                    <span id="id_confirm_{{id}}" class="confirm-friend-request material-icons p-1"
                        onclick='triggerAcceptFriendRequest("{{pending_friend_request_id}}")'>check</span>
                </div>
            </div>
            {% endif %}

            <div class="card m-2 px-4 pb-4">
                <!-- Cancel Friend Request / Send Friend Request / Remove Friend -->
                {% if is_friend == False and is_self == False %}
                <!-- You sent them a request -->
                {% if request_sent == 1 %}
                <div class="d-flex flex-column align-items-center pt-4">
                    <button class="btn btn-danger" id="id_cancel_friend_request_btn">
                        Cancel Friend Request
                    </button>
                </div>
                {% endif %}
                <!-- No requests have been sent -->
                {% if request_sent == -1 %}
                <div class="d-flex flex-column align-items-center pt-4">
                    <button class="btn btn-primary" id="id_send_friend_request_btn">
                        Send Friend Request
                    </button>
                </div>
                {% endif %}
                {% endif %}


                {% if is_friend %}
                <div class="dropdown pt-4 m-auto">
                    <button class="btn btn-secondary dropdown-toggle friends-btn" type="button" id="id_friends_toggle"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Friends
                    </button>
                    <div class="dropdown-menu" aria-labelledby="id_friends_toggle">
                        <a class="dropdown-item" href="#" onclick="removeFriend('{{id}}', onFriendRemoved)">Unfriend</a>
                    </div>
                </div>
                {% endif %}

                <!-- TODO -->
                <!-- Friend list link -->
                <div class="d-flex flex-column pt-4">
                    <a href="#">
                        <div class="d-flex flex-row align-items-center justify-content-center icon-container">
                            <span class="material-icons mr-2 friends-icon">contact_page</span><span
                                class="friend-text">Friends (0)</span>
                        </div>
                    </a>
                </div>

            </div>

            <!-- TODO -->
            {#% if friend_requests %#}
            <div class="card m-2 px-4 pb-4">
                <!-- Friend requests -->
                <div class="d-flex flex-column pt-4">
                    <a href="#">
                        <div class="d-flex flex-row align-items-center justify-content-center icon-container">
                            <span class="material-icons mr-2 person-add-icon">person_add</span><span
                                class="friend-text">Friend Requests (0)</span>
                        </div>
                    </a>
                </div>
            </div>
            {#% endif %#}

            {% if is_friend %}
            <div class="d-flex flex-row align-items-center btn btn-primary m-2 px-4"
                onclick="createOrReturnPrivateChat('{{id}}')">
                <span class="material-icons m-auto">
                    message
                </span>
                <span class="message-btn-text m-auto pl-2">Message</span>
            </div>
            {% endif %}

        </div>
        {% endif %}


    </div>
</div>


<script type="text/javascript">

    // called from base_js.html
    //preloadImage("{{profile_image|safe}}", 'id_profile_image')

    function onFriendRequestSent() {
        location.reload();
    }

    function onFriendRequestCancelled() {
        location.reload();
    }

    function onFriendRemoved() {
        location.reload();
    }

    function onFriendRequestAccepted() {
        location.reload();
    }

    function onFriendRequestDeclined() {
        location.reload();
    }


    var sendFriendRequestBtn = document.getElementById("id_send_friend_request_btn")
    if (sendFriendRequestBtn != null) {
        sendFriendRequestBtn.addEventListener("click", function () {
            //sendFriendRequest("{{id}}", onFriendRequestSent)
        })
    }

    var cancelFriendRequestBtn = document.getElementById("id_cancel_friend_request_btn")
    if (cancelFriendRequestBtn != null) {
        cancelFriendRequestBtn.addEventListener("click", function () {
            //cancelFriendRequest("{{id}}", onFriendRequestCancelled)
        })
    }

    var removeFriendBtn = document.getElementById("id_unfriend_btn")
    if (removeFriendBtn != null) {
        removeFriendBtn.addEventListener("click", function () {
            //removeFriend("{{id}}", onFriendRemoved)
        })
    }

    function triggerAcceptFriendRequest(friend_request_id) {
        //acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
    }

    function triggerDeclineFriendRequest(friend_request_id) {
        //declineFriendRequest(friend_request_id, onFriendRequestDeclined)
    }

</script>

{#% include 'snippets/send_friend_request.html' %#}
{#% include 'snippets/accept_friend_request.html' %#}
{#% include 'snippets/decline_friend_request.html' %#}
{#% include 'snippets/cancel_friend_request.html' %#}
{#% include 'snippets/remove_friend.html' %#}
{#% include 'chat/create_or_return_private_chat.html' %#}



{% endblock %}

templates/DjangoChatApp/edit_account.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card profile-card">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<div class="mb-2" id="id_image_crop_confirm">
		  			<span id="id_cancel" class="material-icons">cancel</span>
		  			<span id="id_confirm" class="material-icons">check</span>
		  		</div>
		  		<div class="image-container" id="id_image_container">
	  				<img class="border border-dark rounded-circle img-fluid mx-auto profile-image" id="id_profile_image_display" src="{{form.initial.profile_image.url}}" alt="codingwithmitch logo">
					<div class="middle" id="id_middle_container">
						<div class="text" id="id_text">Edit</div>
					</div>
		  		</div>
		  		<form class="form-signin" method="post" enctype="multipart/form-data">{% csrf_token %}
		  			<input class="d-none" type="file" name="profile_image" id="id_profile_image" onchange="readURL(this)">
			  		<h6 class="mt-4 field-heading">Email</h6>
			  		<input type="email" name="email" id="id_input_email" class="form-control" placeholder="Email address" required autofocus value={{form.initial.email}}>
			  		<h6 class="mt-4 field-heading">Username</h6>
			  		<input type="text" name="username" id="id_input_username" class="form-control" placeholder="Username" required
					value="{{form.initial.username}}">
					<div class="mt-4 checkbox">
						<label>
							<input type="checkbox" name="hide_email" id="id_input_hide_email" {% if form.initial.hide_email %}checked{%endif%}>
							Hide Email
						</label>
			  			
					</div>

					{% for field in form %}
					<p>
					{% for error in field.errors %}
					<p style="color: red">{{ error }}</p>
					{% endfor %}
					</p>
					{% endfor %}
					{% if form.non_field_errors %}
					<div style="color: red">
					<p>{{form.non_field_errors}}</p>
					</div>

					{% endif %}

					<div class="d-flex flex-column mt-4">
						<button class="mt-4 btn btn-primary flex-grow-1" type="submit">Save</button>
					</div>
					
				</form>

		  	</div>
		  </div>
		</div>
	</div>
</div>


<script type="text/javascript">

	enableImageOverlay()

	/*
		Called when a new image is selected from file chooser dialog
	*/
	function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
            	disableImageOverlay()
            	var image = e.target.result
            	var imageField = document.getElementById('id_profile_image_display')
                imageField.src = image
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

	function enableImageOverlay(){
		var text = document.getElementById("id_text")
		text.style.backgroundColor = "#0066ff"
		text.style.color = "white"
		text.style.fontSize = "16px"
		text.style.padding = "16px 32px"
		text.style.cursor = "pointer"

		var profileImage = document.getElementById("id_profile_image")
		profileImage.style.opacity = "1"
		profileImage.style.display = "block"
		profileImage.style.width = "100%"
		profileImage.style.height = "auto"
		profileImage.style.transition = ".5s ease"
		profileImage.style.backfaceVisibility  = "hidden"
		profileImage.style.cursor = "pointer"

		var middleContainer = document.getElementById("id_middle_container")
		middleContainer.style.transition = ".5s ease"
		middleContainer.style.opacity = "0"
		middleContainer.style.position = "absolute"
		middleContainer.style.top = "50%"
		middleContainer.style.left = "50%"
		middleContainer.style.transform = "translate(-50%, -50%)"
		middleContainer.style.textAlign = "center"

		var imageContainer = document.getElementById("id_image_container")
		imageContainer.addEventListener("mouseover", function( event ) { 
			profileImage.style.opacity = "0.3"
			middleContainer.style.opacity = "1"
		})

		imageContainer.addEventListener("mouseout", function( event ) { 
			profileImage.style.opacity = "1"
			middleContainer.style.opacity = "0"
		})

		imageContainer.addEventListener("click", function(event){
			document.getElementById('id_profile_image').click();
		});

		var cropConfirm = document.getElementById("id_image_crop_confirm")
		cropConfirm.classList.remove("d-flex")
		cropConfirm.classList.remove("flex-row")
		cropConfirm.classList.remove("justify-content-between")
		cropConfirm.classList.add("d-none")
		
	}

	function disableImageOverlay(){
		var profileImage = document.getElementById("id_profile_image_display")
		var middleContainer = document.getElementById("id_middle_container")
		var imageContainer = document.getElementById("id_image_container")
		var text = document.getElementById("id_text")

		imageContainer.removeEventListener("mouseover", function( event ) { 
			profileImage.style.opacity = "0.3"
			middleContainer.style.opacity = "1"
		})

		imageContainer.removeEventListener("mouseout", function( event ) { 
			profileImage.style.opacity = "1"
			middleContainer.style.opacity = "0"
		})

		profileImage.style.opacity = "1"
		middleContainer.style.opacity = "0"
		text.style.cursor = "default"
		text.style.opacity = "0"

		document.getElementById('id_image_container').removeEventListener("click", function(event){
			event.preventDefault();
			// do nothing
		});
		document.getElementById('id_profile_image').addEventListener("click", function(event){
			event.preventDefault();
			// do nothing
		});

		var cropConfirm = document.getElementById("id_image_crop_confirm")
		cropConfirm.classList.remove("d-none")
		cropConfirm.classList.add("d-flex")
		cropConfirm.classList.add("flex-row")
		cropConfirm.classList.add("justify-content-between")

		var confirm = document.getElementById("id_confirm")
		confirm.addEventListener("click", function(event){
			// TODO
			enableImageOverlay()
		})

		var cancel = document.getElementById("id_cancel")
		cancel.addEventListener("click", function(event){
			console.log("Reloading window...")
			window.location.reload();
		})
	}
</script>


{% endblock content %}

templates/DjangoChatApp/index.html
{% extends '../base.html' %}
{% load static %}

{% block content %}

{% endblock %}

templates/DjangoChatApp/search_results.html
<!-- search_results.html -->

{% extends '../base.html' %}
{% load static %}

{% block content %}



<div class="container">
    <div class="card p-2">

        {% if accounts %}
        <div class="d-flex flex-row flex-wrap">
            {% for account in accounts %}
            <div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
                <a class="profile-link" href="{% url 'account_view' user_id=account.0.id %}">
                    <div class="card-image m-2">
                        <img class="img-fluid profile-image" src="{{account.0.profile_image.url}}" alt="">
                    </div>
                </a>
                <a class="profile-link" href="{% url 'account_view' user_id=account.0.id %}">
                    <div class="card-center px-2">
                        <h4 class="card-title">{{account.0.username}}</h4>
                        {% if account.1 %}
                        <p class="card-text"><a href="#" onclick="createOrReturnPrivateChat('{{account.0.id}}')">Send a
                                Message</a></p>
                        {% endif %}

                    </div>
                </a>
                <div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
                    {% if account.1 %}
                    <div class="d-flex flex-row friends-text-container p-3">
                        <p class="friends-text m-auto">
                            Friends
                        </p>
                        <span class="material-icons checkmark-icon m-auto pl-2">
                            check_circle_outline
                        </span>
                    </div>
                    {% else %}
                    {% if account.0 != request.user %}
                    <div class="d-flex flex-row friends-text-container p-3">
                        <p class="friends-text m-auto">
                            Not Friends
                        </p>
                        <span class="material-icons cancel-icon m-auto pl-2">cancel</span>
                    </div>
                    {% endif %}
                    {% endif %}
                    {% if account.0 == request.user %}
                    <div class="d-flex flex-row friends-text-container p-3">
                        <p class="friends-text m-auto">
                            This is you
                        </p>
                        <span class="material-icons m-auto pl-2">
                            person_pin
                        </span>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% if forloop.counter|divisibleby:2 %}
        </div>
        <div class="d-flex flex-row flex-wrap">
            {% endif %}

            {% endfor %}

            {% else %}
            <!-- If no friends -->
            <div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
                <p>No results</p>
            </div>
            {% endif %}
        </div>
    </div>

</div>


{#% include 'chat/create_or_return_private_chat.html' %#}

<script type="text/javascript">
    function createOrReturnPrivateChat(user_id) {
        // Just a placeholder
    }
</script>

{% endblock %}